### ISSUE TITLE
Displaying multiple of the same commands

### ISSUE THREAD

**Issue by mikecarr** [Salandora/OctoPrint-SystemCommandEditor#23] opened 2020-05-07 16:10 UTC
System Command Editor (0.3.4)
OctoPrint: 1.4.0 

After adding commands it displays multiple entries
![image](https://user-images.githubusercontent.com/1970342/81318012-7138a380-9042-11ea-9278-f50f02c12a51.png)

**Comment by Salandora** [comment] 2020-05-07 20:04
Duplicate of #21 
I'm aware of the bug, I do not recommend using this plugin right now but manually editing the config.yml file according to the docs listed in #21 

Bug will be fixed with a complete rewrite of the underlaying system, because of some major bug there.

**Closed as completed by Salandora** 2020-05-07 20:04 UTC
Labels: duplicate
